name: Playwright Tests
on:
  push:
    branches: [ main, master, develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        cd TodoApp.Ui
        npm install  # ci yerine install kullanarak kilidi kırıyoruz
    - name: Install Playwright
      run: |
        cd TodoApp.Ui
        npx playwright install --with-deps
    - name: Run Tests
      run: |
        cd TodoApp.Ui
        npx playwright test
